#!/bin/bash
set -ex

cd "$(dirname "$0")/.."

mkdir -p "$SWIFT_PM_EXTERNAL_LIBS/include/" && cp -r .build/artifacts/tensorflow-lite-swift/TensorFlowLiteC.xcframework/android-arm64-v8a/Headers/* "$SWIFT_PM_EXTERNAL_LIBS/include/"

mkdir -p "$SWIFT_PM_EXTERNAL_LIBS/arm64-v8a/" && cp .build/artifacts/tensorflow-lite-swift/TensorFlowLiteC.xcframework/android-arm64-v8a/libtensorflowlite_jni.so "$SWIFT_PM_EXTERNAL_LIBS/arm64-v8a/"
mkdir -p "$SWIFT_PM_EXTERNAL_LIBS/armeabi-v7a/" && cp .build/artifacts/tensorflow-lite-swift/TensorFlowLiteC.xcframework/android-armeabi-v7a/libtensorflowlite_jni.so "$SWIFT_PM_EXTERNAL_LIBS/armeabi-v7a/"
mkdir -p "$SWIFT_PM_EXTERNAL_LIBS/x86/" && cp .build/artifacts/tensorflow-lite-swift/TensorFlowLiteC.xcframework/android-x86/libtensorflowlite_jni.so "$SWIFT_PM_EXTERNAL_LIBS/x86/"
mkdir -p "$SWIFT_PM_EXTERNAL_LIBS/x86_64/" && cp .build/artifacts/tensorflow-lite-swift/TensorFlowLiteC.xcframework/android-x86_64/libtensorflowlite_jni.so "$SWIFT_PM_EXTERNAL_LIBS/x86_64/"
